server:
  port: 8001
spring:
  application:
    name: spider-service    # 项目名称尽量用小写
#  boot:
#    admin:
#      url: http://localhost:8090
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

logging:
  file: ./log/analyzer.log
  level:
    root: INFO



hope2:
  service:
    spider: http://127.0.0.1:8001
    stock: http://127.0.0.1:8002
    analyzer: http://127.0.0.1:8003
  data:
    path: ./target/data
  gugudata:
    api:
      key:
        us: xxx
        hk: yyy